"""Seed the database with realistic United Hebrew test data.

Creates 12 units (4 subacute, 8 LT), a full-staff roster sized to cover the
current calendar demand, 1 month of schedule, hours ledger entries, callouts,
and a few exclusions. Pulls Kronos-shape worked hours from
``artifacts/timeclock/pay_period_summary.csv`` (generated by
``scripts/generate_timeclock_data.py``) so all 214 employees end up with
ledger rows for every cycle in the dummy window — not just the ~25 in the
hand-curated BASE_HOURS list. Without this step the workload monitor's bars
read 0h for the auto-generated roster.

Usage:
    python scripts/generate_timeclock_data.py    # produces the CSVs
    python scripts/seed_dev_data.py              # auto-loads them at the end
"""
from __future__ import annotations

import csv
import sys
from datetime import date, datetime, timezone
from pathlib import Path

import httpx

BASE_URL = "http://localhost:8000"


def _print_response(label: str, resp: httpx.Response) -> None:
    """Safe response printer — falls back to raw text when JSON parse fails.

    The bulk-sync endpoints occasionally return an empty body or an HTML
    error page (FastAPI default handler). The original ``resp.json()`` call
    crashed mid-print with no clue what the server actually said. This
    helper prints the parsed JSON when it can, otherwise the status code
    plus the raw text + content-type so the failure is debuggable.
    """
    try:
        parsed = resp.json()
    except ValueError:
        body_preview = resp.text[:500] if resp.text else "<empty body>"
        ctype = resp.headers.get("content-type", "?")
        print(
            f"{label}: {resp.status_code} [{ctype}] non-JSON response — "
            f"{body_preview!r}"
        )
        return
    print(f"{label}: {resp.status_code} — {parsed}")

UNIT_ZIP_CODES = {
    "U-SA1": "11374",
    "U-SA2": "11373",
    "U-SA3": "11368",
    "U-SA4": "11372",
    "U-LT1": "11415",
    "U-LT2": "11418",
    "U-LT3": "11432",
    "U-LT4": "11367",
    "U-LT5": "11004",
    "U-LT6": "11423",
    "U-LT7": "11426",
    "U-LT8": "11429",
}

FULL_STAFF_HEADCOUNT = 214

CROSS_TRAIN_BUDDIES = {
    "U-SA1": "U-SA2",
    "U-SA2": "U-SA1",
    "U-SA3": "U-SA4",
    "U-SA4": "U-SA3",
    "U-LT1": "U-LT2",
    "U-LT2": "U-LT1",
    "U-LT3": "U-LT4",
    "U-LT4": "U-LT3",
    "U-LT5": "U-LT6",
    "U-LT6": "U-LT5",
    "U-LT7": "U-LT8",
    "U-LT8": "U-LT7",
}

ADDITIONAL_RN_BY_UNIT = {
    "U-SA1": 7,
    "U-SA2": 8,
    "U-SA3": 8,
    "U-SA4": 8,
    "U-LT1": 4,
    "U-LT2": 4,
    "U-LT3": 4,
    "U-LT4": 4,
    "U-LT5": 5,
    "U-LT6": 5,
    "U-LT7": 5,
    "U-LT8": 5,
}

ADDITIONAL_CNA_BY_UNIT = {
    "U-SA1": 9,
    "U-SA2": 10,
    "U-SA3": 6,
    "U-SA4": 6,
    "U-LT1": 14,
    "U-LT2": 14,
    "U-LT3": 10,
    "U-LT4": 10,
    "U-LT5": 6,
    "U-LT6": 12,
    "U-LT7": 12,
    "U-LT8": 12,
}

GENERATED_FIRST_NAMES = [
    "Amelia",
    "Benjamin",
    "Camila",
    "Daniel",
    "Elena",
    "Felix",
    "Gianna",
    "Hudson",
    "Isla",
    "Julian",
    "Kiara",
    "Landon",
    "Maya",
    "Nolan",
    "Olivia",
    "Paige",
    "Quinn",
    "Rafael",
    "Sienna",
    "Theo",
]

GENERATED_LAST_NAMES = [
    "Bennett",
    "Castillo",
    "Delgado",
    "Ellis",
    "Foster",
    "Griffin",
    "Hayes",
    "Jordan",
    "Morrison",
    "Perry",
    "Ramirez",
    "Sullivan",
]

BASE_STAFF = [
    # Subacute RNs
    {"employee_id": "RN001", "name": "Maria Rodriguez", "license": "RN", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-SA1"], "home_unit_id": "U-SA1", "cross_trained_units": ["U-SA2"], "hire_date": "2019-03-15"},
    {"employee_id": "RN002", "name": "James Thompson", "license": "RN", "employment_class": "PT", "zip_code": "10301", "home_unit_id": "U-SA2", "cross_trained_units": ["U-SA1"], "hire_date": "2017-06-01"},
    {"employee_id": "RN003", "name": "Priya Patel", "license": "RN", "employment_class": "PER_DIEM", "zip_code": "11432", "home_unit_id": "U-SA1", "cross_trained_units": [], "hire_date": "2020-09-01"},
    {"employee_id": "RN004", "name": "Carlos Mendez", "license": "RN", "employment_class": "FT", "zip_code": "07030", "home_unit_id": "U-SA3", "cross_trained_units": ["U-SA1", "U-SA2"], "hire_date": "2015-01-10"},
    # LT RNs
    {"employee_id": "RN005", "name": "Lisa Chen", "license": "RN", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-LT1"], "home_unit_id": "U-LT1", "cross_trained_units": [], "hire_date": "2021-02-15"},
    {"employee_id": "RN006", "name": "Robert Williams", "license": "RN", "employment_class": "PT", "zip_code": "11432", "home_unit_id": "U-LT2", "cross_trained_units": ["U-LT1"], "hire_date": "2018-11-01"},
    # LPNs
    {"employee_id": "LPN001", "name": "Sarah Kim", "license": "LPN", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-LT3"], "home_unit_id": "U-LT3", "cross_trained_units": ["U-LT1", "U-LT2"], "hire_date": "2018-09-01"},
    {"employee_id": "LPN002", "name": "Angela Davis", "license": "LPN", "employment_class": "PT", "zip_code": "10301", "home_unit_id": "U-LT4", "cross_trained_units": [], "hire_date": "2022-05-15"},
    {"employee_id": "LPN003", "name": "Mark Johnson", "license": "LPN", "employment_class": "FT", "zip_code": "07030", "home_unit_id": "U-SA4", "cross_trained_units": ["U-SA1"], "hire_date": "2019-07-01"},
    # Subacute CNAs
    {"employee_id": "CNA001", "name": "Aisha Johnson", "license": "CNA", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-SA1"], "home_unit_id": "U-SA1", "cross_trained_units": ["U-SA2", "U-LT1"], "hire_date": "2020-06-01"},
    {"employee_id": "CNA002", "name": "David Brown", "license": "CNA", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-SA1"], "home_unit_id": "U-SA1", "cross_trained_units": [], "hire_date": "2019-01-15"},
    {"employee_id": "CNA003", "name": "Fatima Ali", "license": "CNA", "employment_class": "FT", "zip_code": "11432", "home_unit_id": "U-SA2", "cross_trained_units": ["U-SA1"], "hire_date": "2021-03-01"},
    {"employee_id": "CNA004", "name": "Mike Smith", "license": "CNA", "employment_class": "PT", "zip_code": "10301", "home_unit_id": "U-SA2", "cross_trained_units": [], "hire_date": "2023-11-01"},
    {"employee_id": "CNA005", "name": "Jennifer Garcia", "license": "CNA", "employment_class": "PER_DIEM", "zip_code": UNIT_ZIP_CODES["U-SA3"], "home_unit_id": "U-SA3", "cross_trained_units": ["U-SA1", "U-SA2"], "hire_date": "2018-04-15"},
    {"employee_id": "CNA006", "name": "Omar Hassan", "license": "CNA", "employment_class": "FT", "zip_code": "07030", "home_unit_id": "U-SA4", "cross_trained_units": [], "hire_date": "2025-12-01"},
    # LT CNAs
    {"employee_id": "CNA007", "name": "Patricia Lee", "license": "CNA", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-LT1"], "home_unit_id": "U-LT1", "cross_trained_units": ["U-LT2"], "hire_date": "2019-08-01"},
    {"employee_id": "CNA008", "name": "William Taylor", "license": "CNA", "employment_class": "FT", "zip_code": "11432", "home_unit_id": "U-LT1", "cross_trained_units": [], "hire_date": "2020-12-15"},
    {"employee_id": "CNA009", "name": "Rosa Martinez", "license": "CNA", "employment_class": "PT", "zip_code": UNIT_ZIP_CODES["U-LT2"], "home_unit_id": "U-LT2", "cross_trained_units": ["U-LT1", "U-LT3"], "hire_date": "2017-05-01"},
    {"employee_id": "CNA010", "name": "Kevin Nguyen", "license": "CNA", "employment_class": "FT", "zip_code": "10301", "home_unit_id": "U-LT2", "cross_trained_units": [], "hire_date": "2022-02-01"},
    {"employee_id": "CNA011", "name": "Diana Wilson", "license": "CNA", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-LT3"], "home_unit_id": "U-LT3", "cross_trained_units": ["U-LT4"], "hire_date": "2021-06-15"},
    {"employee_id": "CNA012", "name": "Brian Clark", "license": "CNA", "employment_class": "PER_DIEM", "zip_code": "07030", "home_unit_id": "U-LT3", "cross_trained_units": [], "hire_date": "2023-01-01"},
    {"employee_id": "CNA013", "name": "Maria Santos", "license": "CNA", "employment_class": "FT", "zip_code": "11432", "home_unit_id": "U-LT4", "cross_trained_units": ["U-LT3"], "hire_date": "2018-10-01"},
    {"employee_id": "CNA014", "name": "Thomas Anderson", "license": "CNA", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-LT4"], "home_unit_id": "U-LT4", "cross_trained_units": [], "hire_date": "2024-03-15"},
    {"employee_id": "CNA015", "name": "Grace Park", "license": "CNA", "employment_class": "PT", "zip_code": UNIT_ZIP_CODES["U-LT5"], "home_unit_id": "U-LT5", "cross_trained_units": ["U-LT4"], "hire_date": "2020-01-01"},
    # PCTs
    {"employee_id": "PCT001", "name": "Ahmad Ibrahim", "license": "PCT", "employment_class": "FT", "zip_code": UNIT_ZIP_CODES["U-SA1"], "home_unit_id": "U-SA1", "cross_trained_units": ["U-SA2"], "hire_date": "2021-09-01"},
    {"employee_id": "PCT002", "name": "Nicole Brown", "license": "PCT", "employment_class": "FT", "zip_code": "11432", "home_unit_id": "U-LT5", "cross_trained_units": [], "hire_date": "2022-07-15"},
]

BASE_HOURS = [
    # CNAs with varied hours
    {"employee_id": "CNA001", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "CNA002", "cycle_start_date": "2026-04-06", "hours_this_cycle": 33.0, "shift_count_this_biweek": 4},
    {"employee_id": "CNA003", "cycle_start_date": "2026-04-06", "hours_this_cycle": 16.5, "shift_count_this_biweek": 2},
    {"employee_id": "CNA004", "cycle_start_date": "2026-04-06", "hours_this_cycle": 8.25, "shift_count_this_biweek": 1},
    {"employee_id": "CNA005", "cycle_start_date": "2026-04-06", "hours_this_cycle": 0.0, "shift_count_this_biweek": 0},
    {"employee_id": "CNA006", "cycle_start_date": "2026-04-06", "hours_this_cycle": 0.0, "shift_count_this_biweek": 0},
    {"employee_id": "CNA007", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "CNA008", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "CNA009", "cycle_start_date": "2026-04-06", "hours_this_cycle": 16.5, "shift_count_this_biweek": 2},
    {"employee_id": "CNA010", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "CNA011", "cycle_start_date": "2026-04-06", "hours_this_cycle": 16.5, "shift_count_this_biweek": 2},
    {"employee_id": "CNA012", "cycle_start_date": "2026-04-06", "hours_this_cycle": 0.0, "shift_count_this_biweek": 0},
    {"employee_id": "CNA013", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "CNA014", "cycle_start_date": "2026-04-06", "hours_this_cycle": 16.5, "shift_count_this_biweek": 2},
    {"employee_id": "CNA015", "cycle_start_date": "2026-04-06", "hours_this_cycle": 8.25, "shift_count_this_biweek": 1},
    {"employee_id": "PCT001", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
    {"employee_id": "PCT002", "cycle_start_date": "2026-04-06", "hours_this_cycle": 8.25, "shift_count_this_biweek": 1},
    # RNs with biweekly tracking
    {"employee_id": "RN001", "cycle_start_date": "2026-03-30", "hours_this_cycle": 66.0, "shift_count_this_biweek": 8},
    {"employee_id": "RN002", "cycle_start_date": "2026-03-30", "hours_this_cycle": 49.5, "shift_count_this_biweek": 6},
    {"employee_id": "RN003", "cycle_start_date": "2026-03-30", "hours_this_cycle": 16.5, "shift_count_this_biweek": 2},
    {"employee_id": "RN004", "cycle_start_date": "2026-03-30", "hours_this_cycle": 74.25, "shift_count_this_biweek": 9},
    {"employee_id": "RN005", "cycle_start_date": "2026-03-30", "hours_this_cycle": 57.75, "shift_count_this_biweek": 7},
    {"employee_id": "RN006", "cycle_start_date": "2026-03-30", "hours_this_cycle": 41.25, "shift_count_this_biweek": 5},
    {"employee_id": "LPN001", "cycle_start_date": "2026-04-06", "hours_this_cycle": 33.0, "shift_count_this_biweek": 4},
    {"employee_id": "LPN002", "cycle_start_date": "2026-04-06", "hours_this_cycle": 0.0, "shift_count_this_biweek": 0},
    {"employee_id": "LPN003", "cycle_start_date": "2026-04-06", "hours_this_cycle": 24.75, "shift_count_this_biweek": 3},
]


def _make_staff_record(
    employee_id: str,
    name: str,
    license: str,
    employment_class: str,
    home_unit_id: str,
    hire_date: str,
    cross_trained_units: list[str] | None = None,
    zip_code: str | None = None,
) -> dict[str, object]:
    return {
        "employee_id": employee_id,
        "name": name,
        "license": license,
        "employment_class": employment_class,
        "zip_code": zip_code or UNIT_ZIP_CODES[home_unit_id],
        "home_unit_id": home_unit_id,
        "cross_trained_units": cross_trained_units or [],
        "hire_date": hire_date,
    }


def _generated_name(sequence: int) -> str:
    first = GENERATED_FIRST_NAMES[sequence % len(GENERATED_FIRST_NAMES)]
    last = GENERATED_LAST_NAMES[
        (sequence // len(GENERATED_FIRST_NAMES)) % len(GENERATED_LAST_NAMES)
    ]
    return f"{first} {last}"


def _generated_hire_date(sequence: int) -> str:
    hire_year = 2016 + (sequence % 9)
    hire_month = (sequence % 12) + 1
    hire_day = ((sequence * 3) % 28) + 1
    return f"{hire_year:04d}-{hire_month:02d}-{hire_day:02d}"


def _generated_cross_training(unit_id: str, sequence: int) -> list[str]:
    buddy = CROSS_TRAIN_BUDDIES.get(unit_id)
    if not buddy or sequence % 2:
        return []
    return [buddy]


def build_staff_records() -> list[dict[str, object]]:
    staff = list(BASE_STAFF)
    name_sequence = 0
    next_rn = 7
    next_cna = 16

    for unit_id, count in ADDITIONAL_RN_BY_UNIT.items():
        for unit_sequence in range(count):
            staff.append(
                _make_staff_record(
                    employee_id=f"RN{next_rn:03d}",
                    name=_generated_name(name_sequence),
                    license="RN",
                    employment_class="FT",
                    home_unit_id=unit_id,
                    hire_date=_generated_hire_date(name_sequence),
                    cross_trained_units=_generated_cross_training(
                        unit_id, unit_sequence
                    ),
                )
            )
            next_rn += 1
            name_sequence += 1

    for unit_id, count in ADDITIONAL_CNA_BY_UNIT.items():
        for unit_sequence in range(count):
            staff.append(
                _make_staff_record(
                    employee_id=f"CNA{next_cna:03d}",
                    name=_generated_name(name_sequence),
                    license="CNA",
                    employment_class="FT",
                    home_unit_id=unit_id,
                    hire_date=_generated_hire_date(name_sequence),
                    cross_trained_units=_generated_cross_training(
                        unit_id, unit_sequence
                    ),
                )
            )
            next_cna += 1
            name_sequence += 1

    if len(staff) != FULL_STAFF_HEADCOUNT:
        raise ValueError(
            f"Expected {FULL_STAFF_HEADCOUNT} seeded staff records, got {len(staff)}"
        )
    return staff


def build_hours_records() -> list[dict[str, object]]:
    records = list(BASE_HOURS)
    existing_employee_ids = {record["employee_id"] for record in records}

    for staff in build_staff_records():
        employee_id = str(staff["employee_id"])
        if employee_id in existing_employee_ids:
            continue
        cycle_start_date = "2026-03-30" if staff["license"] == "RN" else "2026-04-06"
        records.append(
            {
                "employee_id": employee_id,
                "cycle_start_date": cycle_start_date,
                "hours_this_cycle": 0.0,
                "shift_count_this_biweek": 0,
            }
        )

    return records


def seed_units():
    """Seed units via a direct approach (no sync endpoint for units yet)."""
    print("Note: Units must be created directly in DB or via migration seed.")
    print("Skipping unit creation — use Alembic seed or manual insert.")


def seed_staff():
    """Seed the full roster required to cover the current calendar demand."""
    staff = build_staff_records()
    resp = httpx.post(f"{BASE_URL}/sync/staff", json={"records": staff})
    _print_response("Staff sync", resp)


def seed_schedule():
    """Seed the full month of April 2026 with schedule entries."""
    entries = []

    # Staff assignments for 4 key units (realistic coverage)
    schedule_map = {
        # Subacute units — heavier staffing
        "U-SA1": {
            "DAY": ["RN001", "CNA001", "CNA002", "PCT001"],
            "EVENING": ["RN003", "CNA001", "CNA005"],
            "NIGHT": ["RN001", "CNA002"],
        },
        "U-SA2": {
            "DAY": ["RN002", "CNA003", "CNA004"],
            "EVENING": ["RN002", "CNA003"],
            "NIGHT": ["RN004", "CNA004"],
        },
        # LT units
        "U-LT1": {
            "DAY": ["RN005", "CNA007", "CNA008"],
            "EVENING": ["LPN001", "CNA007"],
            "NIGHT": ["RN005", "CNA008"],
        },
        "U-LT2": {
            "DAY": ["RN006", "CNA009", "CNA010"],
            "EVENING": ["RN006", "CNA009"],
            "NIGHT": ["LPN001", "CNA010"],
        },
    }

    # Weekend alternative staffing (reduced)
    weekend_map = {
        "U-SA1": {
            "DAY": ["RN001", "CNA001", "PCT001"],
            "EVENING": ["RN003", "CNA005"],
            "NIGHT": ["CNA002"],
        },
        "U-SA2": {
            "DAY": ["RN002", "CNA003"],
            "EVENING": ["CNA003"],
            "NIGHT": ["RN004"],
        },
        "U-LT1": {
            "DAY": ["RN005", "CNA007"],
            "EVENING": ["CNA007"],
            "NIGHT": ["CNA008"],
        },
        "U-LT2": {
            "DAY": ["RN006", "CNA009"],
            "EVENING": ["CNA009"],
            "NIGHT": ["CNA010"],
        },
    }

    # Cross-unit coverage demos: some days show SUBACUTE staff covering LT
    cross_coverage = [
        # Day 10: CNA001 (home=U-SA1 subacute) covers U-LT1 DAY shift
        ("2026-04-10", "U-LT1", "DAY", "CNA001"),
        # Day 15: CNA005 (home=U-SA3 subacute) covers U-LT2 EVENING
        ("2026-04-15", "U-LT2", "EVENING", "CNA005"),
        # Day 20: RN004 (home=U-SA3 subacute) covers U-LT1 NIGHT
        ("2026-04-20", "U-LT1", "NIGHT", "RN004"),
    ]

    for d in range(1, 31):
        shift_date = f"2026-04-{d:02d}"
        dow = date(2026, 4, d).weekday()  # 0=Mon, 6=Sun
        is_weekend = dow >= 5

        active_map = weekend_map if is_weekend else schedule_map

        for unit_id, shift_staff in active_map.items():
            for shift_label, emp_ids in shift_staff.items():
                for emp_id in emp_ids:
                    entries.append({
                        "employee_id": emp_id,
                        "unit_id": unit_id,
                        "shift_date": shift_date,
                        "shift_label": shift_label,
                        "is_published": True,
                    })

    # Add cross-coverage entries
    for shift_date, unit_id, shift_label, emp_id in cross_coverage:
        entries.append({
            "employee_id": emp_id,
            "unit_id": unit_id,
            "shift_date": shift_date,
            "shift_label": shift_label,
            "is_published": True,
        })

    resp = httpx.post(f"{BASE_URL}/sync/schedule", json={"schedule_entries": entries})
    _print_response("Schedule sync", resp)


def seed_callouts():
    """Seed callout records to create red slots on specific days."""
    callouts = [
        {
            "employee_id": "CNA001",
            "unit_id": "U-SA1",
            "shift_date": "2026-04-08",
            "shift_label": "DAY",
            "reason": "Sick call",
            "reported_at": "2026-04-08T06:30:00Z",
        },
        {
            "employee_id": "CNA003",
            "unit_id": "U-SA2",
            "shift_date": "2026-04-14",
            "shift_label": "EVENING",
            "reason": "Family emergency",
            "reported_at": "2026-04-14T12:00:00Z",
        },
        {
            "employee_id": "CNA007",
            "unit_id": "U-LT1",
            "shift_date": "2026-04-17",
            "shift_label": "DAY",
            "reason": "Car trouble",
            "reported_at": "2026-04-17T06:00:00Z",
        },
        {
            "employee_id": "RN001",
            "unit_id": "U-SA1",
            "shift_date": "2026-04-22",
            "shift_label": "NIGHT",
            "reason": "Illness",
            "reported_at": "2026-04-22T20:00:00Z",
        },
        {
            "employee_id": "CNA009",
            "unit_id": "U-LT2",
            "shift_date": "2026-04-28",
            "shift_label": "EVENING",
            "reason": "Personal day",
            "reported_at": "2026-04-28T10:00:00Z",
        },
    ]

    resp = httpx.post(
        f"{BASE_URL}/sync/schedule",
        json={"callouts": callouts},
    )
    _print_response("Callout sync", resp)


TIMECLOCK_CSV_PATH = (
    Path(__file__).resolve().parents[1]
    / "artifacts"
    / "timeclock"
    / "pay_period_summary.csv"
)


def _load_timeclock_records() -> list[dict[str, object]]:
    """Convert pay_period_summary.csv rows into HoursLedger sync records.

    Worked hours = REG + OT + DT + HOL (matches
    ``app.services.timeclock_ingest.summary_to_ledger_record`` — kept in sync
    so seed-time and runtime ingest produce identical ledger state). PTO and
    SICK are deliberately excluded because the workload bar shows time on
    the floor, not total paid time.
    """
    if not TIMECLOCK_CSV_PATH.exists():
        return []
    records: list[dict[str, object]] = []
    with TIMECLOCK_CSV_PATH.open(newline="") as f:
        for row in csv.DictReader(f):
            worked = (
                float(row["regular_hours"])
                + float(row["overtime_hours"])
                + float(row["doubletime_hours"])
                + float(row["holiday_hours"])
            )
            records.append(
                {
                    "employee_id": row["person_number"],
                    "cycle_start_date": row["pay_period_start"],
                    "hours_this_cycle": round(worked, 2),
                    "shift_count_this_biweek": int(row["shift_count"]),
                }
            )
    return records


def seed_hours():
    """Seed hours ledger for the current pay cycle.

    Two-phase seed so the workload monitor reads correctly for any view
    month:

      1. Post the curated BASE_HOURS first — these establish the seed
         "current cycle" for the ~25 hand-named employees and create
         zero-hour placeholders for everyone else.
      2. Post every (employee, cycle) pair from the time-clock CSV —
         covers all 214 employees across all 8 biweekly cycles in the
         dummy window (Jan 19 -> Apr 27 2026). Upsert semantics mean
         the CSV values overwrite step 1 wherever they overlap.

    If the CSV is missing (the user hasn't run generate_timeclock_data.py
    yet), step 2 is skipped with a warning instead of failing.
    """
    base_records = build_hours_records()
    resp = httpx.post(f"{BASE_URL}/sync/hours", json={"records": base_records})
    _print_response("Hours sync (base)", resp)

    timeclock_records = _load_timeclock_records()
    if not timeclock_records:
        print(
            "  [warn] artifacts/timeclock/pay_period_summary.csv not found; "
            "skipping time-clock ingest. Run "
            "`python scripts/generate_timeclock_data.py` then re-run this "
            "seed script to populate the workload monitor with realistic "
            "worked hours."
        )
        return

    # Chunk the upload + bump the timeout. ``sync_hours`` does an N+1
    # SELECT per record (no bulk upsert), so 1712 rows in a single request
    # can easily blow past the default 5-second httpx timeout. Chunks of
    # ~200 keep each request comfortably under a second and let us see
    # progress in the seed log.
    chunk_size = 200
    timeout = 60.0
    total_created = 0
    total_updated = 0
    for offset in range(0, len(timeclock_records), chunk_size):
        chunk = timeclock_records[offset : offset + chunk_size]
        resp = httpx.post(
            f"{BASE_URL}/sync/hours",
            json={"records": chunk},
            timeout=timeout,
        )
        try:
            payload = resp.json()
            total_created += payload.get("created", 0)
            total_updated += payload.get("updated", 0)
        except ValueError:
            _print_response(
                f"Hours sync (time-clock chunk @ {offset})", resp
            )
            return
    print(
        f"Hours sync (time-clock CSV): {len(timeclock_records)} rows in "
        f"{(len(timeclock_records) + chunk_size - 1) // chunk_size} chunks "
        f"— created={total_created} updated={total_updated}"
    )


def test_callout():
    """Simulate a call-out and get recommendations."""
    print("\n--- Simulating CNA call-out on U-SA1 DAY shift ---")
    resp = httpx.post(
        f"{BASE_URL}/callouts",
        json={
            "callout_employee_id": "CNA001",
            "unit_id": "U-SA1",
            "shift_date": "2026-04-09",
            "shift_label": "DAY",
        },
        timeout=30.0,
    )
    if resp.status_code == 200:
        data = resp.json()
        print(f"Callout ID: {data['callout_id']}")
        print(f"Filter stats: {data['filter_stats']}")
        print(f"Top candidates:")
        for c in data["candidates"][:5]:
            print(f"  #{c['rank']} {c['name']} ({c['license']}) — score {c['score']:.3f}")
            print(f"     {c['rationale']}")
    else:
        print(f"Error: {resp.status_code} — {resp.text}")


def regenerate_timeclock_data() -> None:
    """Regenerate the Kronos dummy CSVs ending on today's date.

    Runs before the time-clock ingest step in ``seed_hours`` so the simulated
    clock data always reflects "history through right now" — matching how a
    real Kronos integration behaves. Run ``python scripts/seed_dev_data.py
    --no-timeclock-regen`` to skip this step (useful when you've manually
    generated a non-default range, e.g. for a back-dated demo).

    Lazy-imported to avoid the circular import with
    ``scripts/generate_timeclock_data.py`` (which itself imports
    ``build_staff_records`` from this module).
    """
    from scripts.generate_timeclock_data import generate_and_write

    print("\n--- Regenerating time-clock dummy data (end=today) ---")
    generate_and_write()


if __name__ == "__main__":
    if "--no-timeclock-regen" not in sys.argv:
        regenerate_timeclock_data()
    print(f"\nSeeding against {BASE_URL}")
    seed_staff()
    seed_schedule()
    seed_callouts()
    seed_hours()
    if "--test" in sys.argv:
        test_callout()
    print("\nDone!")
